//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.18 at 07:30:24 �ߌ� JST 
//


package examples.bathory.dto.fileExample1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="empNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="empName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="mgrId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hiredate" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sal" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="deptId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "employee")
public class Employee {

    @XmlAttribute
    protected String empNo;
    @XmlAttribute
    protected String empName;
    @XmlAttribute
    protected String mgrId;
    @XmlAttribute
    protected String hiredate;
    @XmlAttribute
    protected String sal;
    @XmlAttribute
    protected String deptId;

    /**
     * Gets the value of the empNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpNo() {
        return empNo;
    }

    /**
     * Sets the value of the empNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpNo(String value) {
        this.empNo = value;
    }

    /**
     * Gets the value of the empName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * Sets the value of the empName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmpName(String value) {
        this.empName = value;
    }

    /**
     * Gets the value of the mgrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMgrId() {
        return mgrId;
    }

    /**
     * Sets the value of the mgrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMgrId(String value) {
        this.mgrId = value;
    }

    /**
     * Gets the value of the hiredate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHiredate() {
        return hiredate;
    }

    /**
     * Sets the value of the hiredate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHiredate(String value) {
        this.hiredate = value;
    }

    /**
     * Gets the value of the sal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSal() {
        return sal;
    }

    /**
     * Sets the value of the sal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSal(String value) {
        this.sal = value;
    }

    /**
     * Gets the value of the deptId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * Sets the value of the deptId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeptId(String value) {
        this.deptId = value;
    }

}
